package com.sinensia.ligaGFT.business.model;

public enum TipoLance {

	GOL_LOCAL, GOL_VISITANTE, GOL_LOCAL_ANULADO, GOL_VISITANTE_ANULADO, TARJETA_ROJA, TARJETA_AMARILLA, VAR,
	FUERA_JUEGO, PENALTY, PENALTY_ANULADO, PARADA, CORNER, TIRO_LIBRE, CAMBIO, MINUTOS_EXTRA, INICIO, FIN_PRIMERA_PARTE,
	INICIO_SEGUNDA_PARTE, FIN;

}